### ISSUE TITLE
Document for project

### ISSUE THREAD

**Issue by alirezaseif28** [rabbal/MaterialAngularTabLayout#1]
hello @rabbal .
I hope you're good luck.
I wanted to give you a little documentation about this project whenever you could. About moduleFactory and injector. Thank you so much for you.

**Comment by rabbal** [comment]
Hi
You can use below article that related to the repository.
<span dir="rtl">
[بارگذاری پویای کامپوننت‌های Angular به همراه امکان Lazy loading پویای ماژول‌ها](https://www.dotnettips.info/post/2953/)
</span>

**Comment by alirezaseif28** [comment]
ok .thanks @rabbal .
