### ISSUE TITLE
ngModulefactoryloader is deprecated

### ISSUE THREAD

**Issue by mmdsharifi** [rabbal/MaterialAngularTabLayout#2]
According to Angular [documentation](https://angular.io/api/core/NgModuleFactoryLoader) `NgModuleFactoryLoader` has deprecated, and might be removed in the next version of Angular.

The new way of loading modules in Angular 8.x or upper is using `import`: 
For example:
 ```ts
 {
        path: '',
        loadChildren: () =>
          import('./lazy/lazy.module').then(
            m => m.LazyModule
          )
 }
```
Obviously this project needs to upgrade to the last version of Angular witch currently is 9.x. 
I'll submit a PR for changes that mentioned.

Thanks

**Comment by rabbal** [comment]
Thank you, mohmmad
I merged your PR
